### ISSUE TITLE
Remove folders too

### ISSUE THREAD

**Issue by alexandrechaudet** [StephanThierry/ftp-delete-action#3]
Hello,

Is it possible to update it to remove folders too ? I would to use it but I need to clean a directory (all files & folders of the workingDir passed in parameter).

- name: Clean Folder
        uses: StephanThierry/ftp-delete-action@releases/v1
        with:
          host: ftp.rockett.fr
          user: My_Rockett_User
          password: ${{ secrets.FTP_PASSWORD }}
          remoteFiles: "*"
          workingDir: "/MyFolder"
          ignoreSSL: "1"

>>>>>>result>>>>>>

rm: Access failed: 550 src: Is a directory

Regards,

Alexandre

**Comment by StephanThierry** [comment]
I've made a new branch with a new param: remoteDirectories
test it by changing "uses" to:
uses: StephanThierry/ftp-delete-action@v1.1-beta
...and then:
remoteDirectories: "/folder/you/want/to/delete;/maybe/another"

Let me know if it solves your issue.

**Comment by alexandrechaudet** [comment]
Can I put "*" in "remoteDirectories" ? It select only directories in the workingDir ? I don't want to explode my ftp ^^

It throws an exception when removing files with "*" for files because it tried to remove a directory "rm: Access failed: 550 src: Is a directory". Maybe when we put "*" in files you must 'ls' only files in the workingDir / and when we put "*" in removeDirectories you must 'ls' only directories in the workingDir ?

**Comment by alexandrechaudet** [comment]
I fork it to : https://github.com/Rockett53/ftp-clean-directory-action
It works on v5 : Rockett53/ftp-clean-directory-action@releases/v5
I do this :
1 - Delete recursively the workingDir
2 - Create the workingDir

**Comment by StephanThierry** [comment]
The workingDir is the base directory of all other operations - the starting point. 
It works like you would use "cd" on the commandline before you type other commands - for example: 

remoteDirectories: "/public_html/log;/public_html/temp;"

The idea is to instead set: 
workingDir: "/public_html" - and the 
remoteDirectories: "log;temp"

If you want to delete "*" from some starting point - just put the name of the folder you want to delete
remoteDirectories: "public_html"

Your other publish action should then create whatever folder you need.


Seems you have solved your usecase but I can't use it in my action because you are 1). deleting the workingDir - that is not how what param is intended. 2). creating a new dir, that is not the intention of this action.

/Stephan

**Comment by stabas** [comment]
@StephanThierry 
what would be correct use for parameters if ihave following domain/ftp structure:

some.domain.org/pull/123

i want to use this ftp delete action (latest released version) on closing pull requests to delete "123" folder or at least whats inside

remoteFiles: "*" (still required ?)
remoteDirectories: "/123"
workingDir: "/pull"

would this be correct?

**Comment by StephanThierry** [comment]
Use workingDir ´: your/path, remoteFiles: * - if you want to delete everything in your/path
Use: remoteDirectories - if you want to delete the directory (not just the files)

**Comment by stabas** [comment]
so "remoteFiles" is not required if i want to delete folder? just to be sure, because readme says so :)

**Comment by jemshit** [comment]
I couldn't make this work (sftp), it does nothing and keeps running indefinitely @StephanThierry :

```yml
    - name: Delete Feature folder from FTP server
      uses: StephanThierry/ftp-delete-action@v2.1
      with:
        host: ${{ secrets.FTP_SERVER_IP }} # also tried "sftp://MY_IP:22"
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteFiles: "" # also tried "*"
        remoteDirectories: "alpha/${{ env.FEATURE_NAME }}"
        workingDir: "/dirBase"
        ignoreSSL: "1"
        # Also tried options: "-p 20"
````

It must delete `/dirBase/alpha/myFeatureName` directory and everything in it 

Logs:

```
rm -f -r "alpha/demo" 2>/dev/null; 
---- Resolving host address...
---- IPv6 is not supported or configured
---- 1 address found: ***
---- Connecting to *** (***) port 22
<--- SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
**** Peer closed connection
---- Closing control socket
---- Connecting to *** (***) port 22
<--- SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
```

I can see `lftp -d -u myUsername,myPassword sftp://MY_IP -p 22 -e "cd /dirBase; ls"` works on my terminal. But if I use `host: 'sftp://MY_IP'` and `options: "-d -p 22"` I get this log:

```
---- Running connect program (ssh -a -x -s -l *** -p 22 MY_IP sftp)
rm -f -r "alpha/demo" 2>/dev/null; 
---> sending a packet, length=5, type=1(INIT), id=0
<--- sh: ssh: not found
**** pty read: pseudo-tty: I/O error
**** sh: ssh: not found
---- Disconnecting
```
